#!/bin/bash


eww daemon
# Apply wallpaper
swww-daemon && swww img "$(cat $BACKGROUND_FILE)" & eww open-many bar activate-linux 



# MONITORS=$(hyprctl monitors -j | jq 'map({key: .id | tostring, value: .name}) | from_entries')
# COUNT=$(jq --argjson monitors "${MONITORS}" "len($MONITORS)")

