#!/bin/bash
eww open-many bar activate-linux

# MONITORS=$(hyprctl monitors -j | jq 'map({key: .id | tostring, value: .name}) | from_entries')
# COUNT=$(jq --argjson monitors "${MONITORS}" "len($MONITORS)")

